-- migration-v84 — P8.6 : connecteur de tickets. GitHub Issues d'abord, l'outil
-- ITSM de MIP (ServiceNow, sous réserve de confirmation) ensuite.
--
-- Additive et rejouable, PostgreSQL 15 à 17. S'applique APRÈS migration-v73
-- (error_issue_ticket, le lien manuel) et refuse de s'appliquer sans elle.
--
--   1. ticket_integration : une configuration par (app, fournisseur, cible).
--      Le secret n'est PAS ici : la colonne porte une RÉFÉRENCE, et une
--      contrainte le garantit structurellement (cf. § 1).
--   2. ticket_outbox : une demande de création par issue et par intégration,
--      clé d'idempotence unique, backoff, et un état `delivery_uncertain` qui
--      appelle un opérateur au lieu de créer un second ticket.
--   3. ticket_webhook_event : une livraison entrante par (intégration, id de
--      livraison), unique — c'est la protection contre le rejeu.
--   4. error_issue_ticket gagne provider / external_id / integration_id SANS
--      que le lien manuel change de forme : toutes les colonnes ajoutées sont
--      nullables, et `origin` vaut `manual` par défaut.
--   5. RLS, droits, et `erase_app_data` qui atteint la nouvelle configuration.
--
-- POURQUOI LE SECRET N'EST PAS DANS CETTE BASE. Un jeton de création de ticket
-- écrit dans une colonne de configuration finit recopié dans un export, un dump
-- de recette, une capture d'écran d'admin. `credential_ref` ne peut contenir que
-- deux formes — `env:NOM_DE_VARIABLE` (le gestionnaire de secrets du runtime) ou
-- `enc:v1:…` (chiffré par une clé serveur SÉPARÉE, hors base) — et la contrainte
-- `ticket_integration_credential_v84` refuse tout le reste. Un `ghp_…` collé
-- dans ce champ fait échouer l'écriture ; ce n'est pas une convention, c'est une
-- contrainte.
--
-- POURQUOI `delivery_uncertain` EST UN ÉTAT ET PAS UNE ERREUR. Un délai
-- d'attente dépassé APRÈS l'envoi et AVANT l'accusé ne dit pas si le ticket
-- existe. Réessayer crée un doublon chez le client ; abandonner perd la demande.
-- Le connecteur cherche d'abord le ticket par la référence MIP portée dans son
-- corps ; si cette recherche n'aboutit pas, la ligne s'arrête ici et attend un
-- humain. Aucun chemin de ce fichier ne rejoue une création après une incertitude.
--
-- FENÊTRE DE DÉPLOIEMENT. Le code P8.6 publié avant ce fichier détecte l'absence
-- des tables : la console masque la surface d'intégration et répond 503 aux
-- mutations, le dispatcher de tickets ne trouve rien à livrer.
--
-- VERROUS. Aucune table chaude n'est touchée : `error_issue_ticket` ne porte que
-- des liens saisis à la main. `lock_timeout` borne chaque attente ; s'il expire,
-- le fichier entier est annulé et le déploiement rejoué.
set local lock_timeout = '5s';

do $$
begin
  if to_regclass('public.error_issue_ticket') is null then
    raise exception 'v84 : migration-v73 (error_issue_ticket) doit être appliquée avant ce fichier';
  end if;
end $$;

-- ── 1. Configuration d'une intégration ──────────────────────────────────────
-- `target` est la cible CONFIRMÉE à la configuration (`owner/repo` pour GitHub),
-- jamais déduite du remote git de MIP : le dépôt du produit n'est pas le dépôt
-- où l'on ouvre les tickets d'un client, et un défaut « pratique » serait la
-- première fuite. `verified_at` porte la recette réelle : tant qu'il est NULL,
-- l'intégration est configurée mais pas éprouvée, et la console ne propose pas
-- de créer de ticket avec.
create table if not exists ticket_integration (
  id                  bigint generated by default as identity primary key,
  app_id              text not null,
  provider            text not null,
  target              text not null,
  credential_ref      text not null,
  webhook_secret_ref  text,
  enabled             boolean not null default false,
  config_version      integer not null default 1,
  config              jsonb not null default '{}'::jsonb,
  state               text not null default 'active',
  last_error          text,
  verified_at         timestamptz,
  created_by          text,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),
  constraint ticket_integration_cible_v84 unique (app_id, provider, target),
  constraint ticket_integration_v84 check (
    char_length(app_id) between 1 and 200 and
    provider in ('github') and
    char_length(target) between 3 and 200 and target ~ '^[A-Za-z0-9][A-Za-z0-9._-]*/[A-Za-z0-9][A-Za-z0-9._-]*$' and
    config_version >= 1 and
    state in ('active', 'degraded') and
    jsonb_typeof(config) = 'object' and octet_length(config::text) <= 4096 and
    (last_error is null or last_error ~ '^[a-z][a-z0-9_]{0,59}$')
  ),
  -- La forme du champ EST la garantie : ni jeton, ni mot de passe, ni URL
  -- signée ne passe ce filtre. Une valeur en clair échoue à l'écriture.
  --
  -- La borne haute est un `char_length`, PAS une répétition bornée : le moteur
  -- d'expressions régulières de PostgreSQL refuse un `{16,4096}` (« invalid
  -- repetition count(s) », plafond à 255) — et il le refuse à l'ÉVALUATION,
  -- donc la contrainte se serait créée sans bruit pour n'échouer qu'à la
  -- première écriture, en production.
  constraint ticket_integration_credential_v84 check (
    credential_ref ~ '^env:[A-Z][A-Z0-9_]{0,63}$' or
    (credential_ref ~ '^enc:v1:[A-Za-z0-9+/=]+$' and char_length(credential_ref) between 23 and 4096)
  ),
  constraint ticket_integration_webhook_v84 check (
    webhook_secret_ref is null or
    webhook_secret_ref ~ '^env:[A-Z][A-Z0-9_]{0,63}$' or
    (webhook_secret_ref ~ '^enc:v1:[A-Za-z0-9+/=]+$' and char_length(webhook_secret_ref) between 23 and 4096)
  )
);

create index if not exists idx_ticket_integration_app_v84
  on ticket_integration (app_id, enabled, provider);

comment on table ticket_integration is
  'Connecteur de tickets app-scopé (P8.6). GitHub Issues est l''implémentation actuelle ; la cible '
  'reste l''outil ITSM de MIP (ServiceNow, sous réserve de confirmation). Le secret n''est jamais ici.';
comment on column ticket_integration.credential_ref is
  'RÉFÉRENCE au secret : env:<VARIABLE> du gestionnaire de secrets, ou enc:v1:<chiffré par clé serveur séparée>';
comment on column ticket_integration.verified_at is
  'Date de la recette réelle (un vrai ticket créé et relu). NULL = configurée mais jamais éprouvée';
comment on column ticket_integration.state is
  'active ; degraded = le fournisseur refuse le jeton ou la cible — la collecte RUM n''est jamais bloquée pour autant';

-- ── 2. File de sortie ───────────────────────────────────────────────────────
-- `idempotency_key` est DÉTERMINISTE : `ticket:<integration_id>:<issue_id>`. Deux
-- clics, deux onglets ou deux rejeux du 202 retombent sur la même ligne, donc sur
-- le même ticket. Elle est unique globalement, comme le demande le contrat.
--
-- `payload` fige le titre, la description et le lien EXACTEMENT tels que l'écran
-- les a montrés à l'opérateur : le dispatcher envoie ce qui est là, il ne
-- recompose rien. Sans ça, « l'aperçu » et « ce qui part » seraient deux
-- calculs, donc deux vérités.
create table if not exists ticket_outbox (
  id                    bigint generated by default as identity primary key,
  app_id                text not null,
  integration_id        bigint not null references ticket_integration (id) on delete cascade,
  issue_id              uuid not null,
  idempotency_key       text not null,
  state                 text not null default 'pending',
  attempts              integer not null default 0,
  next_attempt_at       timestamptz not null default now(),
  external_id           text,
  external_url          text,
  payload               jsonb not null,
  uncertain             boolean not null default false,
  last_error            text,
  requested_by_user_id  bigint references console_user (id) on delete set null,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now(),
  sent_at               timestamptz,
  constraint ticket_outbox_issue_v84 foreign key (app_id, issue_id)
    references error_issue (app_id, id) on delete cascade,
  constraint ticket_outbox_cle_v84 unique (idempotency_key),
  constraint ticket_outbox_v84 check (
    char_length(idempotency_key) between 1 and 200 and
    state in ('pending', 'sent', 'failed', 'delivery_uncertain', 'cancelled') and
    attempts between 0 and 100 and
    jsonb_typeof(payload) = 'object' and octet_length(payload::text) <= 16384 and
    (external_id is null or (char_length(external_id) between 1 and 200 and external_id ~ '^[!-~]+$')) and
    (external_url is null or (char_length(external_url) between 9 and 2048 and external_url ~ '^https://[!-~]+$')) and
    (last_error is null or last_error ~ '^[a-z][a-z0-9_]{0,59}$') and
    -- Un état `sent` sans identifiant distant serait un succès sans preuve.
    ((state = 'sent') = (sent_at is not null)) and
    (state <> 'sent' or external_id is not null)
  )
);

create index if not exists idx_ticket_outbox_pending_v84
  on ticket_outbox (next_attempt_at, id) where state = 'pending';
create index if not exists idx_ticket_outbox_issue_v84
  on ticket_outbox (app_id, issue_id, created_at desc, id desc);
create index if not exists idx_ticket_outbox_integration_v84
  on ticket_outbox (integration_id, state);

comment on table ticket_outbox is
  'File de création de tickets (P8.6) : une ligne par issue et par intégration, clé idempotente, '
  'backoff, et delivery_uncertain plutôt qu''une seconde création';
comment on column ticket_outbox.uncertain is
  'La tentative précédente a pu créer le ticket chez le fournisseur : chercher par référence MIP avant tout envoi';
comment on column ticket_outbox.payload is
  'Titre, description et lien FIGÉS à la demande — exactement ce que l''aperçu admin a montré';
comment on column ticket_outbox.last_error is
  'CODE d''échec, jamais un message : un message de fournisseur peut citer la donnée qu''on refuse de sortir';

-- ── 3. Livraisons entrantes ─────────────────────────────────────────────────
-- L'unicité (intégration, livraison) EST la protection contre le rejeu : une
-- même livraison rejouée par le fournisseur — ou par un attaquant qui aurait
-- capté un corps signé — est reconnue et ignorée.
create table if not exists ticket_webhook_event (
  id              bigint generated by default as identity primary key,
  app_id          text not null,
  integration_id  bigint not null references ticket_integration (id) on delete cascade,
  delivery_id     text not null,
  event_type      text,
  external_id     text,
  received_at     timestamptz not null default now(),
  status          text not null,
  constraint ticket_webhook_event_livraison_v84 unique (integration_id, delivery_id),
  constraint ticket_webhook_event_v84 check (
    char_length(delivery_id) between 1 and 200 and delivery_id ~ '^[!-~]+$' and
    (event_type is null or (char_length(event_type) between 1 and 100 and event_type ~ '^[a-z][a-z0-9_.-]*$')) and
    (external_id is null or (char_length(external_id) between 1 and 200 and external_id ~ '^[!-~]+$')) and
    status in ('applied', 'ignored', 'unmapped', 'unknown_ticket', 'duplicate', 'rejected')
  )
);

create index if not exists idx_ticket_webhook_event_recu_v84
  on ticket_webhook_event (integration_id, received_at desc, id desc);

comment on table ticket_webhook_event is
  'Journal des livraisons entrantes d''un fournisseur de tickets (P8.6) ; unique par (intégration, livraison), '
  'sans aucun détail RUM';

-- ── 4. Le lien P5 s'enrichit sans changer de forme ──────────────────────────
-- Toutes les colonnes sont nullables et `origin` vaut `manual` : une ligne
-- existante reste valide telle quelle, et un lien collé à la main continue de
-- fonctionner sans qu'aucune intégration existe.
alter table error_issue_ticket add column if not exists provider           text;
alter table error_issue_ticket add column if not exists external_id        text;
alter table error_issue_ticket add column if not exists integration_id     bigint;
alter table error_issue_ticket add column if not exists origin             text not null default 'manual';
alter table error_issue_ticket add column if not exists provider_state     text;
alter table error_issue_ticket add column if not exists provider_synced_at timestamptz;

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'error_issue_ticket_integration_v84') then
    alter table error_issue_ticket
      add constraint error_issue_ticket_integration_v84
      foreign key (integration_id) references ticket_integration (id) on delete set null;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'error_issue_ticket_provider_v84') then
    alter table error_issue_ticket
      add constraint error_issue_ticket_provider_v84 check (
        origin in ('manual', 'connector') and
        (provider is null or provider in ('github')) and
        -- Un lien de connecteur SAIT d'où il vient ; un lien manuel n'invente
        -- pas un fournisseur pour faire joli.
        ((origin = 'connector') = (provider is not null and external_id is not null)) and
        (external_id is null or (char_length(external_id) between 1 and 200 and external_id ~ '^[!-~]+$')) and
        (provider_state is null or provider_state in ('open', 'closed', 'unknown'))
      );
  end if;
end $$;

create unique index if not exists idx_error_issue_ticket_externe_v84
  on error_issue_ticket (integration_id, external_id) where integration_id is not null;

comment on column error_issue_ticket.origin is
  'manual : URL collée par un opérateur (P5.6, fonctionne sans connecteur) ; connector : créé par P8.6';
comment on column error_issue_ticket.provider_state is
  'Dernier état connu chez le fournisseur, tel qu''un webhook l''a dit. MIP reste source de vérité pour `ignored`';

-- ── 5. Une décision de statut VENUE D'UN FOURNISSEUR entre au journal ───────
--
-- v73 interdisait une ligne d'activité `status` posée par le système : à
-- l'époque, la seule décision automatique était une régression, et elle a son
-- propre `kind`. Un fournisseur de tickets en apporte une seconde — « ce ticket
-- a été fermé », traduit selon le mapping EXPLICITEMENT configuré.
--
-- La relaxation est étroite, et c'est voulu : une ligne `status` posée par le
-- système doit porter une `event_key`. Cette clé est l'identifiant de livraison
-- du fournisseur ; l'index unique de v73 sur (app, issue, event_key) fait donc
-- qu'une livraison rejouée n'écrit rien une seconde fois. Sans elle, un webhook
-- rejoué empilerait des lignes d'historique identiques — et c'est exactement
-- l'oscillation qu'on veut interdire.
--
-- LA CONTRAINTE N'EST PAS RECOPIÉE : on part de sa définition COURANTE, on y
-- insère la clause, et on échoue bruyamment si le point d'ancrage n'apparaît pas
-- exactement une fois. Même geste que pour `erase_app_data`, même raison.
do $$
declare
  def   text;
  ancre constant text := '((kind <> ''status''::text) OR (actor_kind = ''user''::text))';
  ajout constant text := '((kind <> ''status''::text) OR (actor_kind = ''user''::text) OR (event_key IS NOT NULL))';
begin
  select pg_get_constraintdef(c.oid) into def
    from pg_constraint c join pg_class t on t.oid = c.conrelid
    join pg_namespace ns on ns.oid = t.relnamespace
   where ns.nspname = 'public' and t.relname = 'error_issue_activity'
     and c.conname = 'error_issue_activity_v73';
  if def is null then
    -- Déjà relaxée (rejeu du fichier) : rien à faire. Absente pour une autre
    -- raison : v73 manque, et la garde en tête de fichier l'aurait dit.
    if exists (select 1 from pg_constraint where conname = 'error_issue_activity_v84') then
      return;
    end if;
    raise exception 'v84: error_issue_activity_v73 introuvable — appliquer v73 d''abord';
  end if;
  if (length(def) - length(replace(def, ancre, ''))) / length(ancre) <> 1 then
    raise exception 'v84: point d''insertion ambigu dans error_issue_activity_v73 (% occurrences)',
      (length(def) - length(replace(def, ancre, ''))) / length(ancre);
  end if;
  -- `CHECK (…)` → on garde l'expression telle quelle, clause insérée.
  execute 'alter table error_issue_activity add constraint error_issue_activity_v84 '
       || replace(def, ancre, ajout);
  execute 'alter table error_issue_activity drop constraint error_issue_activity_v73';
end $$;

-- ── 6. RLS et droits ────────────────────────────────────────────────────────
-- Trois tables app-scopées, trois policies explicites : jamais `using (true)`,
-- que la garde structurelle de `verify-tenant-isolation.mjs` refuserait.
--
-- LE SECRET N'EST PAS LISIBLE PAR LA CONSOLE. `console_ro` reçoit un SELECT
-- colonne par colonne, et `credential_ref` / `webhook_secret_ref` n'y sont pas :
-- un viewer — et même la console entière sous ce rôle — ne peut pas lire une
-- référence de secret, encore moins la suivre. Les écritures d'intégration
-- passent par le rôle propriétaire (comme les jetons de source maps), pas par un
-- droit accordé ici.
alter table ticket_integration enable row level security;
drop policy if exists tenant_scope on ticket_integration;
create policy tenant_scope on ticket_integration
  for select to console_ro
  using (app_id = any (current_app_ids()));

alter table ticket_outbox enable row level security;
drop policy if exists tenant_scope on ticket_outbox;
create policy tenant_scope on ticket_outbox
  for select to console_ro
  using (app_id = any (current_app_ids()));

alter table ticket_webhook_event enable row level security;
drop policy if exists tenant_scope on ticket_webhook_event;
create policy tenant_scope on ticket_webhook_event
  for select to console_ro
  using (app_id = any (current_app_ids()));

do $$
begin
  if exists (select 1 from pg_roles where rolname = 'console_ro') then
    revoke all on ticket_integration, ticket_outbox, ticket_webhook_event from console_ro;
    grant select (id, app_id, provider, target, enabled, config_version, config, state,
                  last_error, verified_at, created_by, created_at, updated_at)
      on ticket_integration to console_ro;
    grant select on ticket_outbox, ticket_webhook_event to console_ro;
  end if;
  if exists (select 1 from pg_roles where rolname = 'anon') then
    revoke all on ticket_integration, ticket_outbox, ticket_webhook_event from anon;
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    revoke all on ticket_integration, ticket_outbox, ticket_webhook_event from authenticated;
  end if;
end $$;

-- ── 7. `erase_app_data` atteint la configuration d'intégration ──────────────
--
-- LA DÉFINITION N'EST PAS RECOPIÉE. Recopier une fonction de cent lignes pour y
-- ajouter un `delete` est exactement le geste qui a fait perdre
-- `analytics_saved_view` et `dashboard` entre v79 et v80, puis failli effacer le
-- verrou de P8.1 en v82. On insère donc la ligne manquante dans la définition
-- COURANTE, quelle qu'elle soit, et on échoue bruyamment si le point d'insertion
-- n'est pas trouvé exactement une fois. v85 (P8.7) s'écrit en parallèle de ce
-- fichier : c'est précisément le cas que cette forme protège.
--
-- `ticket_outbox` et `ticket_webhook_event` partent EN CASCADE avec leur
-- intégration ; les liens de ticket partent avec leur issue (v73). Une seule
-- ligne suffit donc, et le test de recette le vérifie contre le catalogue.
do $$
declare
  src   text;
  ancre constant text := E'\n  return result;\n';
  ajout constant text :=
    E'\n  -- v84 (P8.6) : connecteurs de tickets, app-scopés. La file de sortie et le\n'
    '  -- journal des livraisons entrantes partent en cascade avec l''intégration.\n'
    '  delete from ticket_integration where app_id = p_app_id;'
    ' get diagnostics n = row_count; result := result || jsonb_build_object(''ticket_integration'', n);\n'
    '  return result;\n';
begin
  select p.prosrc into src
    from pg_proc p join pg_namespace ns on ns.oid = p.pronamespace
   where ns.nspname = 'public' and p.proname = 'erase_app_data'
     and p.pronargs = 1 and p.proargtypes[0] = 'text'::regtype;
  if src is null then
    raise exception 'v84: erase_app_data(text) introuvable — appliquer v81 d''abord';
  end if;
  -- Déjà posée : rejouer le fichier ne doit pas doubler l'instruction.
  if position('from ticket_integration ' in src) > 0 then
    return;
  end if;
  if (length(src) - length(replace(src, ancre, ''))) / length(ancre) <> 1 then
    raise exception 'v84: point d''insertion ambigu dans erase_app_data (% occurrences)',
      (length(src) - length(replace(src, ancre, ''))) / length(ancre);
  end if;
  execute 'create or replace function erase_app_data(p_app_id text) returns jsonb language plpgsql as '
       || quote_literal(replace(src, ancre, ajout));
end $$;

comment on function erase_app_data(text) is
  'Efface toutes les données d''une application et SUSPEND son ingestion dans le registre, sous le '
  'même verrou. Conserve privacy_erasure_barrier et privacy_erasure_request. Depuis v83, vide aussi '
  'backfill_run ; depuis v84, ticket_integration (et sa file de sortie en cascade). La reprise de '
  'l''ingestion est une opération explicite.';
