-- migration-v73 — P5.6 : triage, régressions et notifications par issue.
--
-- Additive et rejouable, PostgreSQL 15 à 17. S'applique APRÈS migration-v72
-- (error_issue) et refuse de s'appliquer sans elle.
--
--   1. error_issue_ticket : liens de ticket saisis à la main (HTTPS, 2 048
--      caractères, libellé de 120). Aucune synchronisation fournisseur (P8.6).
--   2. error_issue_activity : historique append-only — statut, assignation,
--      commentaire, lien, régression. Jamais de stack, de message d'erreur ni
--      d'identité RUM : seuls des identifiants internes, des releases et du texte
--      saisi par un opérateur, déjà scrubbé par l'écrivain.
--   3. error_issue_notification : outbox des notifications d'issue (nouvelle,
--      régression, pic), une clé d'événement unique par notification, remise au
--      routage existant (route_alert) par route_error_issue_notifications().
--   4. RLS et droits. Les trois tables suivent leur issue par clé étrangère en
--      cascade : purge_rum_app et erase_app_data (v71/v72) ne sont PAS
--      redéfinies, la rétention et l'effacement d'une issue emportent son
--      historique, ses liens et ses notifications.
--   5. Nouvelle issue : l'outbox est écrite par déclencheur, dans la transaction
--      qui crée l'issue. check_new_errors (v64) garde son watermark pour les
--      groupes historiques et ignore désormais les lignes rattachées à une issue.
--   6. Régression : error_issue_record_occurrences(), appelée par l'écrivain dans
--      SA transaction, issue verrouillée — jamais un curseur relu après coup.
--   7. Alertes issue:<uuid> : fenêtre et baseline exactes, no_data explicite,
--      pic remis à l'outbox sous une clé d'événement.
--   8. Livraison : les livraisons sans règle restées en file sont soldées
--      (skipped) avant que le dispatcher local ne les prenne en charge.
--
-- POURQUOI PAS UN CURSEUR. check_new_errors avance un watermark (ingested_at, id) :
-- une transaction qui alloue ses identifiants tôt et valide tard reste derrière
-- le curseur et n'est jamais relue. Ici, la décision est prise dans la
-- transaction qui écrit (régression) ou par déclencheur sur la ligne créée
-- (nouvelle issue), et l'outbox est dépilée par état, pas par identifiant.
--
-- FENÊTRE DE DÉPLOIEMENT. Le code P5.6 publié avant ce fichier détecte l'absence
-- des tables : la console répond 503 aux mutations de triage, le dispatcher et
-- les travaux planifiés gardent leur comportement antérieur.
--
-- VERROUS. Aucune table chaude n'est modifiée : error_issue, alert_rule,
-- alert_event et alert_config sont petites. `lock_timeout` borne chaque attente ;
-- s'il expire, le fichier entier est annulé et le déploiement rejoué.
set local lock_timeout = '5s';

do $$
begin
  if to_regclass('public.error_issue') is null then
    raise exception 'v73 : migration-v72 (error_issue) doit être appliquée avant ce fichier';
  end if;
end $$;

-- ── 1. Liens de ticket ──────────────────────────────────────────────────────
-- ASCII imprimable seulement : l'URL est normalisée par l'écrivain (points de
-- code hors ASCII encodés), et la borne en caractères devient une borne en
-- octets, compatible avec l'index d'unicité.
create table if not exists error_issue_ticket (
  id                  bigint generated by default as identity primary key,
  app_id              text not null,
  issue_id            uuid not null,
  url                 text not null,
  label               text not null,
  created_by_user_id  bigint references console_user (id) on delete set null,
  created_at          timestamptz not null default now(),
  constraint error_issue_ticket_issue_v73 foreign key (app_id, issue_id)
    references error_issue (app_id, id) on delete cascade,
  constraint error_issue_ticket_ref_v73 unique (app_id, issue_id, id),
  constraint error_issue_ticket_url_v73 unique (app_id, issue_id, url),
  constraint error_issue_ticket_v73 check (
    char_length(url) between 9 and 2048 and url ~ '^https://[!-~]+$' and
    char_length(label) between 1 and 120 and label !~ '[[:cntrl:]]'
  )
);

comment on table error_issue_ticket is
  'Liens de ticket attachés à la main à une issue (P5.6) ; aucune donnée n''est envoyée au fournisseur';

-- ── 2. Activité ─────────────────────────────────────────────────────────────
-- Les colonnes utilisateur sont des clés vers console_user, jamais un email. Un
-- compte supprimé laisse NULL : aucune contrainte ne lie donc l'acteur, l'ancien
-- ou le nouvel assigné à leur présence, seulement `actor_kind`.
create table if not exists error_issue_activity (
  id                    bigint generated by default as identity primary key,
  app_id                text not null,
  issue_id              uuid not null,
  kind                  text not null,
  actor_kind            text not null,
  actor_user_id         bigint references console_user (id) on delete set null,
  old_status            text,
  new_status            text,
  old_assignee_user_id  bigint references console_user (id) on delete set null,
  new_assignee_user_id  bigint references console_user (id) on delete set null,
  body                  text,
  legacy_fingerprint    text,
  ticket_id             bigint,
  release               text,
  reference_release     text,
  env                   text,
  event_key             text,
  created_at            timestamptz not null default now(),
  constraint error_issue_activity_issue_v73 foreign key (app_id, issue_id)
    references error_issue (app_id, id) on delete cascade,
  constraint error_issue_activity_ticket_v73 foreign key (app_id, issue_id, ticket_id)
    references error_issue_ticket (app_id, issue_id, id) on delete cascade,
  constraint error_issue_activity_v73 check (
    kind in ('status', 'assignee', 'comment', 'link', 'regression') and
    actor_kind in ('user', 'system') and
    (actor_kind = 'user' or actor_user_id is null) and
    (old_status is null or old_status in ('open', 'for_review', 'resolved', 'ignored')) and
    (new_status is null or new_status in ('open', 'for_review', 'resolved', 'ignored')) and
    (kind not in ('status', 'regression') or (old_status is not null and new_status is not null
                                              and old_status <> new_status)) and
    (kind in ('status', 'regression') or (old_status is null and new_status is null)) and
    (kind <> 'status' or actor_kind = 'user') and
    (kind <> 'regression' or (actor_kind = 'system' and old_status = 'resolved' and new_status = 'open'
                              and release is not null and reference_release is not null and env is not null)) and
    (kind <> 'assignee' or actor_kind = 'user') and
    ((kind = 'comment') = (body is not null)) and
    (body is null or char_length(body) between 1 and 2000) and
    (kind <> 'comment' or actor_kind = 'user' or legacy_fingerprint is not null) and
    (legacy_fingerprint is null or (kind = 'comment' and actor_kind = 'system'
                                    and char_length(legacy_fingerprint) between 1 and 64)) and
    ((kind = 'link') = (ticket_id is not null)) and
    (kind in ('status', 'regression') or (release is null and reference_release is null and env is null)) and
    (release is null or char_length(release) between 1 and 200) and
    (reference_release is null or char_length(reference_release) between 1 and 200) and
    (env is null or char_length(env) between 1 and 120) and
    (event_key is null or char_length(event_key) between 1 and 200)
  )
);

create index if not exists idx_error_issue_activity_issue_v73
  on error_issue_activity (app_id, issue_id, created_at, id);
create unique index if not exists idx_error_issue_activity_event_v73
  on error_issue_activity (app_id, issue_id, event_key) where event_key is not null;

comment on table error_issue_activity is
  'Historique append-only du workflow d''une issue ; ni stack, ni message d''erreur, ni identité RUM';
comment on column error_issue_activity.release is
  'status → resolved : release de référence retenue ; regression : release de l''occurrence qui rouvre';
comment on column error_issue_activity.reference_release is
  'regression : release de référence de la résolution dépassée';
comment on column error_issue_activity.legacy_fingerprint is
  'Note du groupe historique importée une seule fois en commentaire système';
comment on column error_issue_activity.event_key is
  'Clé d''idempotence des lignes système (regression:<résolution>, legacy_note:<empreinte>)';

-- ── 3. Outbox des notifications ─────────────────────────────────────────────
-- `delivered` veut dire REMISE AU ROUTAGE : un alert_event existe et route_alert
-- a mis en file une livraison par canal éligible. Le résultat HTTP de chaque
-- canal se lit dans alert_delivery, pas ici.
create table if not exists error_issue_notification (
  id               bigint generated by default as identity primary key,
  app_id           text not null,
  issue_id         uuid not null,
  kind             text not null,
  rule_id          bigint references alert_rule (id) on delete cascade,
  event_key        text not null,
  payload          jsonb not null,
  state            text not null default 'pending',
  attempts         integer not null default 0,
  next_attempt_at  timestamptz not null default now(),
  last_error       text,
  alert_event_id   bigint references alert_event (id) on delete set null,
  created_at       timestamptz not null default now(),
  delivered_at     timestamptz,
  constraint error_issue_notification_issue_v73 foreign key (app_id, issue_id)
    references error_issue (app_id, id) on delete cascade,
  constraint error_issue_notification_event_v73 unique (event_key),
  constraint error_issue_notification_v73 check (
    kind in ('new', 'regression', 'spike') and
    ((rule_id is not null) = (kind = 'spike')) and
    char_length(event_key) between 1 and 200 and
    jsonb_typeof(payload) = 'object' and octet_length(payload::text) <= 4096 and
    state in ('pending', 'delivered', 'failed') and
    attempts between 0 and 100 and
    (last_error is null or char_length(last_error) <= 500) and
    ((state = 'delivered') = (delivered_at is not null))
  )
);

create index if not exists idx_error_issue_notification_pending_v73
  on error_issue_notification (next_attempt_at, id) where state = 'pending';
create index if not exists idx_error_issue_notification_issue_v73
  on error_issue_notification (app_id, issue_id, created_at);
create index if not exists idx_error_issue_notification_rule_v73
  on error_issue_notification (rule_id) where rule_id is not null;
create index if not exists idx_error_issue_notification_event_v73
  on error_issue_notification (alert_event_id) where alert_event_id is not null;

comment on table error_issue_notification is
  'Outbox des notifications d''issue (new, regression, spike) : clé d''événement unique, charge minimale '
  'sans message ni identité, remise à route_alert par route_error_issue_notifications()';
comment on column error_issue_notification.state is
  'pending : à router ; delivered : alert_event créé et livraisons mises en file ; failed : routage abandonné';

-- ── 4. RLS et droits ────────────────────────────────────────────────────────
-- Tables créées après v47 : policy explicite, fermée sans portée tenant. La
-- console écrit l'activité et les liens, jamais l'outbox ; elle met à jour les
-- seules colonnes de triage d'une issue.
alter table error_issue_ticket enable row level security;
drop policy if exists tenant_scope on error_issue_ticket;
create policy tenant_scope on error_issue_ticket
  for all to console_ro
  using (app_id = any (current_app_ids()))
  with check (app_id = any (current_app_ids()));

alter table error_issue_activity enable row level security;
drop policy if exists tenant_scope on error_issue_activity;
create policy tenant_scope on error_issue_activity
  for all to console_ro
  using (app_id = any (current_app_ids()))
  with check (app_id = any (current_app_ids()));

alter table error_issue_notification enable row level security;
drop policy if exists tenant_scope on error_issue_notification;
create policy tenant_scope on error_issue_notification
  for select to console_ro using (app_id = any (current_app_ids()));

drop policy if exists tenant_triage on error_issue;
create policy tenant_triage on error_issue
  for update to console_ro
  using (app_id = any (current_app_ids()))
  with check (app_id = any (current_app_ids()));

-- Un événement d'alerte né d'une notification d'issue sans règle appartient à
-- l'app de l'issue : même portée que ceux d'une règle ou d'un SLO.
drop policy if exists tenant_scope on alert_event;
create policy tenant_scope on alert_event for all to console_ro using (
  exists (select 1 from alert_rule r where r.id = alert_event.rule_id
            and r.app_id = any (current_app_ids()))
  or
  exists (select 1 from slo s where s.id = alert_event.slo_id
            and s.app_id = any (current_app_ids()))
  or
  exists (select 1 from error_issue_notification n where n.alert_event_id = alert_event.id
            and n.app_id = any (current_app_ids()))
);

do $$
begin
  if exists (select 1 from pg_roles where rolname = 'console_ro') then
    revoke all on error_issue_ticket, error_issue_activity, error_issue_notification from console_ro;
    grant select, insert on error_issue_ticket, error_issue_activity to console_ro;
    grant select on error_issue_notification to console_ro;
    grant update (status, status_source, assignee_user_id, resolved_at, resolved_by_user_id,
                  resolved_release, resolved_env, revision, updated_at) on error_issue to console_ro;
  end if;
  if exists (select 1 from pg_roles where rolname = 'anon') then
    revoke all on error_issue_ticket, error_issue_activity, error_issue_notification from anon;
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    revoke all on error_issue_ticket, error_issue_activity, error_issue_notification from authenticated;
  end if;
end $$;

-- ── 5. Nouvelle issue et groupes historiques ────────────────────────────────
-- Une issue `new` naît avec sa notification, dans la même transaction. `origin =
-- 'migration'` (clé v2 recouvrant un groupe déjà vu) ne notifie pas : c'est ce qui
-- évite de renotifier les groupes connus au basculement. Deux lots concurrents
-- ne créent qu'une issue (unicité v72), donc qu'une notification ; la clé
-- d'événement en est la seconde garantie. Security definer : le déclencheur
-- écrit l'outbox quel que soit le rôle de l'écrivain de l'issue.
create or replace function error_issue_notify_new_v73() returns trigger
language plpgsql security definer set search_path = public, pg_temp as $$
begin
  insert into error_issue_notification (app_id, issue_id, kind, event_key, payload)
  values (
    new.app_id, new.id, 'new', 'new:' || new.id,
    jsonb_build_object(
      'source', 'mip-rum', 'kind', 'new', 'app_id', new.app_id, 'issue_id', new.id,
      'first_release', new.first_release, 'severity', 'warning',
      'text', format('[MIP RUM] Nouvelle issue dans %s%s — /errors/issues/%s?app=%s',
                     new.app_id, coalesce(', release ' || new.first_release, ''), new.id, new.app_id))
  )
  on conflict (event_key) do nothing;
  return null;
end $$;

drop trigger if exists error_issue_notify_new_v73 on error_issue;
create trigger error_issue_notify_new_v73
  after insert on error_issue
  for each row when (new.origin = 'new')
  execute function error_issue_notify_new_v73();

-- Supprimer une issue (rétention, effacement d'app) emporte ses notifications par
-- cascade ; leurs événements d'alerte sans règle ne sont rattachés à rien d'autre
-- et partent avec elles. Ceux d'une règle issue:<uuid> restent à la règle.
create or replace function error_issue_notification_forget_v73() returns trigger
language plpgsql security definer set search_path = public, pg_temp as $$
begin
  delete from alert_event e
   using anciennes a
   where e.id = a.alert_event_id and e.rule_id is null and e.slo_id is null;
  return null;
end $$;

drop trigger if exists error_issue_notification_forget_v73 on error_issue_notification;
create trigger error_issue_notification_forget_v73
  after delete on error_issue_notification
  referencing old table as anciennes
  for each statement
  execute function error_issue_notification_forget_v73();

-- Reprise intégrale de migration-v64 ; seule différence : une ligne rattachée à
-- une issue est notifiée par l'outbox, jamais par ce watermark.
create or replace function check_new_errors() returns integer
  language plpgsql security definer set search_path to 'public', 'pg_temp'
as $function$
declare
  cursor_row record;
  upper_bound record;
  a record;
  fired int := 0;
  ev_id bigint;
  msg text;
  stable text;
begin
  select last_ingested_at, last_error_id
    into cursor_row
    from rum_new_error_watermark
   where singleton = true
   for update;

  select e.ingested_at, e.id into upper_bound
    from rum_error e
   where (e.ingested_at, e.id) > (cursor_row.last_ingested_at, cursor_row.last_error_id)
   order by e.ingested_at desc, e.id desc
   limit 1;

  if not found then
    return 0;
  end if;

  for a in
    select e.app_id, e.fingerprint,
           max(e.error_type) as error_type,
           max(e.message) as sample,
           min(e.ts) as first_seen,
           coalesce(sum(e.occurrences), 0)::bigint as occurrences
      from rum_error e
     where e.fingerprint is not null
       and e.issue_id is null
       and (e.ingested_at, e.id) > (cursor_row.last_ingested_at, cursor_row.last_error_id)
       and (e.ingested_at, e.id) <= (upper_bound.ingested_at, upper_bound.id)
       and not exists (
         select 1
           from rum_error seen
          where seen.app_id = e.app_id
            and seen.fingerprint = e.fingerprint
            and (seen.ingested_at, seen.id) <= (cursor_row.last_ingested_at, cursor_row.last_error_id)
       )
     group by e.app_id, e.fingerprint
  loop
    stable := format('nouvelle erreur %s / app %s', a.fingerprint, a.app_id);
    msg := format('%s — %s « %s » (%s occurrence(s) depuis %s)',
      stable, coalesce(a.error_type, 'Error'), left(coalesce(a.sample, ''), 120), a.occurrences,
      to_char(a.first_seen, 'HH24:MI'));

    if not exists (
      select 1 from alert_event ae
       where ae.rule_id is null and ae.slo_id is null
         and ae.message like '%' || stable || '%'
         and ae.fired_at > now() - interval '24 hours'
    ) then
      insert into alert_event (rule_id, slo_id, value, message, severity)
      values (null, null, a.occurrences, msg, 'warning')
      returning id into ev_id;
      fired := fired + 1;
      perform route_alert(ev_id, a.app_id, 'warning', '[MIP RUM] ' || msg,
        jsonb_build_object('source', 'mip-rum', 'kind', 'new_error', 'app_id', a.app_id,
          'fingerprint', a.fingerprint, 'error_type', a.error_type,
          'occurrences', a.occurrences, 'text', msg));
    end if;
  end loop;

  update rum_new_error_watermark
     set last_ingested_at = upper_bound.ingested_at,
         last_error_id = upper_bound.id
   where singleton = true;
  return fired;
end $function$;

-- ── 6. Régression, dans la transaction de l'écrivain ────────────────────────
-- Appelée par l'écrivain des occurrences, APRÈS leur insertion et AVANT son
-- commit, une issue à la fois dans l'ordre des identifiants (même ordre que la
-- mise à jour de première et dernière vue, donc aucun interblocage entre lots).
-- Ne reçoit que les lignes effectivement insérées : un rejeu n'en fournit aucune.
--
-- Le verrou de ligne sérialise deux écrivains concurrents : le second relit
-- l'issue après le commit du premier, la trouve rouverte et n'écrit rien. Un
-- écrivain qui a commencé tôt et valide tard décide sur l'état validé au moment
-- où il écrit, pas sur un curseur déjà dépassé.
--
-- Régression CONFIRMÉE : issue résolue, occurrence postérieure à la résolution,
-- dans l'env de référence, sur une release dont le premier marqueur de
-- déploiement de cet env est strictement postérieur à celui de la release de
-- référence. Jamais d'ordre lexical ni SemVer : une release sans marqueur, la
-- même release, une plus ancienne ou un env inconnu rendent `reappearance` —
-- « réapparition à vérifier », sans rouvrir. Une issue ignorée, ouverte ou à
-- revoir n'est pas touchée.
create or replace function error_issue_record_occurrences(
  p_app_id text, p_issue_id uuid, p_ts timestamptz[], p_releases text[], p_envs text[]
) returns text
language plpgsql as $$
declare
  i record;
  confirmee record;
  cle text;
begin
  select id, status, resolved_at, resolved_release, resolved_env
    into i
    from error_issue
   where app_id = p_app_id and id = p_issue_id
   for update;
  if not found or i.status <> 'resolved' or i.resolved_at is null then
    return null;
  end if;
  if not exists (select 1 from unnest(p_ts) as t (ts) where t.ts > i.resolved_at) then
    return null;
  end if;

  select o.release, o.ts
    into confirmee
    from unnest(p_ts, p_releases, p_envs) as o (ts, release, env)
    cross join lateral (
      select min(m.ts) as deployed_at
        from deploy_marker m
       where m.app_id = p_app_id and m.env = i.resolved_env and m.version = o.release
    ) occ
   where o.ts > i.resolved_at
     and o.env = i.resolved_env
     and occ.deployed_at > (
       select min(m.ts) from deploy_marker m
        where m.app_id = p_app_id and m.env = i.resolved_env and m.version = i.resolved_release
     )
   order by occ.deployed_at desc, o.ts
   limit 1;
  if not found then
    return 'reappearance';
  end if;

  cle := 'regression:' || (extract(epoch from i.resolved_at) * 1000000)::bigint;
  update error_issue
     set status = 'open', status_source = 'system',
         resolved_at = null, resolved_by_user_id = null, resolved_release = null, resolved_env = null,
         revision = revision + 1, updated_at = now()
   where app_id = p_app_id and id = p_issue_id;
  insert into error_issue_activity
    (app_id, issue_id, kind, actor_kind, old_status, new_status, release, reference_release, env, event_key)
  values
    (p_app_id, p_issue_id, 'regression', 'system', 'resolved', 'open',
     confirmee.release, i.resolved_release, i.resolved_env, cle)
  on conflict (app_id, issue_id, event_key) where event_key is not null do nothing;
  insert into error_issue_notification (app_id, issue_id, kind, event_key, payload)
  values (
    p_app_id, p_issue_id, 'regression', cle || ':' || p_issue_id,
    jsonb_build_object(
      'source', 'mip-rum', 'kind', 'regression', 'app_id', p_app_id, 'issue_id', p_issue_id,
      'release', confirmee.release, 'reference_release', i.resolved_release, 'env', i.resolved_env,
      'severity', 'warning',
      'text', format('[MIP RUM] Régression confirmée dans %s : release %s déployée après %s (env %s) — /errors/issues/%s?app=%s',
                     p_app_id, confirmee.release, i.resolved_release, i.resolved_env, p_issue_id, p_app_id))
  )
  on conflict (event_key) do nothing;
  return 'regression';
end $$;

comment on function error_issue_record_occurrences(text, uuid, timestamptz[], text[], text[]) is
  'Régression confirmée (rouvre, activité, outbox) ou réapparition à vérifier, décidée dans la transaction de l''écrivain';

-- ── 7. Routage de l'outbox ──────────────────────────────────────────────────
-- Étape du tick existant, déclenché par le scheduler ET par le cron GitHub : deux
-- passes simultanées prennent des lignes disjointes (`skip locked`), et une ligne
-- n'est routée qu'une fois (état relu sous verrou). Tout se passe dans la
-- transaction de l'appel : un échec de route_alert annule son alert_event et
-- programme une nouvelle tentative (30 s × 2^tentatives, 5 au plus).
create or replace function route_error_issue_notifications(p_limit integer default 100) returns integer
language plpgsql security definer set search_path = public, pg_temp as $$
declare
  n record;
  ev_id bigint;
  webhook text;
  routees int := 0;
begin
  for n in
    select *
      from error_issue_notification
     where state = 'pending' and next_attempt_at <= now()
     order by next_attempt_at, id
     limit greatest(p_limit, 1)
     for update skip locked
  loop
    begin
      insert into alert_event (rule_id, value, message, severity)
      values (n.rule_id, (n.payload->>'value')::double precision,
              regexp_replace(n.payload->>'text', '^\[MIP RUM\] ', ''), n.payload->>'severity')
      returning id into ev_id;
      if n.rule_id is not null then
        select webhook_url into webhook from alert_rule where id = n.rule_id;
        if webhook is not null then
          insert into alert_delivery (alert_event_id, target) values (ev_id, webhook);
        end if;
      end if;
      perform route_alert(ev_id, n.app_id, n.payload->>'severity', n.payload->>'text', n.payload);
      update error_issue_notification
         set state = 'delivered', alert_event_id = ev_id, attempts = attempts + 1,
             delivered_at = now(), last_error = null
       where id = n.id;
      routees := routees + 1;
    exception when others then
      update error_issue_notification
         set attempts = attempts + 1,
             last_error = left(sqlerrm, 500),
             state = case when attempts + 1 >= 5 then 'failed' else 'pending' end,
             next_attempt_at = now() + interval '30 seconds' * power(2, attempts)
       where id = n.id;
    end;
  end loop;
  return routees;
end $$;

comment on function route_error_issue_notifications(integer) is
  'Remet les notifications d''issue en attente à route_alert (alert_event + livraisons), une seule fois chacune';

-- ── 8. Alertes issue:<uuid> ─────────────────────────────────────────────────
-- `env` n'a de sens que pour une issue (rum_error.env) : il est refusé ailleurs
-- plutôt qu'ignoré en silence. `last_*` rend visible chaque évaluation, dont
-- no_data, que check_alerts traitait jusqu'ici comme une absence d'alerte.
alter table alert_rule
  add column if not exists env text,
  add column if not exists last_evaluated_at timestamptz,
  add column if not exists last_state text,
  add column if not exists last_value double precision,
  add column if not exists last_reason text;

alter table alert_rule drop constraint if exists alert_rule_issue_metric_v73;
alter table alert_rule add constraint alert_rule_issue_metric_v73 check (
  (metric not like 'issue:%' or
   substring(metric from 7) ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$') and
  (env is null or (metric like 'issue:%' and char_length(env) between 1 and 120 and env !~ '[[:cntrl:]]')) and
  (last_state is null or last_state in ('ok', 'breached', 'no_data')) and
  (last_reason is null or char_length(last_reason) <= 300)
);

comment on column alert_rule.env is 'Règle issue:<uuid> : env des occurrences comptées (NULL = tous)';
comment on column alert_rule.last_state is
  'Dernière évaluation par check_alerts : ok, breached ou no_data (données insuffisantes, jamais un zéro)';

-- Depuis quand l'issue est-elle observable ? L'activation v2 en cours de son app :
-- avant elle, aucune occurrence n'est rattachée à une issue et un zéro ne prouve
-- rien. NULL : issue absente de l'app, ou regroupement v2 inactif.
create or replace function issue_metric_observable_since(p_app_id text, p_issue_id uuid) returns timestamptz
language sql stable set search_path = public, pg_temp as $$
  select c.activated_at
    from error_grouping_config c
    join error_issue i on i.app_id = c.app_id and i.id = p_issue_id
   where c.app_id = p_app_id and c.active_version = 2
$$;

-- Occurrences observées d'une issue sur (p_from, p_to] : sommes des répétitions,
-- bots exclus, route et env de la règle, session jointe dans l'app. Les mêmes
-- prédicats servent la fenêtre courante et chaque fenêtre de la baseline. La
-- probabilité d'inclusion minimale (sr + (1 − sr) × esr) signale l'échantillon.
create or replace function issue_metric_window(
  p_app_id text, p_issue_id uuid, p_route text, p_env text, p_from timestamptz, p_to timestamptz
) returns table (occurrences double precision, min_inclusion double precision)
language sql stable set search_path = public, pg_temp as $$
  select coalesce(sum(e.occurrences), 0)::double precision,
         min(case when s.session_id is not null
                  then coalesce(s.sample_rate, 1) + (1 - coalesce(s.sample_rate, 1)) * coalesce(s.error_sample_rate, 1)
             end)::double precision
    from rum_error e
    left join rum_session s on s.app_id = e.app_id and s.session_id = e.session_id
   where e.app_id = p_app_id and e.issue_id = p_issue_id
     and e.ts > p_from and e.ts <= p_to
     and (p_route is null or e.route = p_route)
     and (p_env is null or e.env = p_env)
     and not coalesce(s.is_bot, false)
$$;

-- Baseline exacte : la fenêtre de la règle, finissant à la même heure chacune des
-- semaines précédentes, zéros compris (P4). Seule différence : une fenêtre n'est
-- COMPARABLE que si l'issue y était entièrement observable et ses données encore
-- conservées (rétention de l'app, 30 jours par défaut comme purge_rum_tenants).
-- n compte les fenêtres comparables ; check_alerts en exige 4.
create or replace function issue_metric_baseline(
  p_app_id text, p_issue_id uuid, p_route text, p_env text, p_weeks integer, p_window_minutes integer
) returns table (med double precision, mad double precision, n integer)
language sql stable set search_path = public, pg_temp as $$
  with bornes as (
    select greatest(
             issue_metric_observable_since(p_app_id, p_issue_id),
             now() - make_interval(days => greatest(coalesce(
               (select retention_days from app_registry where app_id = p_app_id), 30), 1))
           ) as depuis
  ), anchors as (
    select now() - make_interval(weeks => g) as hi
      from generate_series(1, greatest(p_weeks, 1)) g, bornes
     where now() - make_interval(weeks => g) - make_interval(mins => greatest(p_window_minutes, 1)) >= bornes.depuis
  ), samples as (
    select w.occurrences as val
      from anchors a
     cross join lateral issue_metric_window(
       p_app_id, p_issue_id, p_route, p_env, a.hi - make_interval(mins => greatest(p_window_minutes, 1)), a.hi) w
  ), m as (
    select percentile_cont(0.5) within group (order by val) v from samples
  )
  select (select v from m),
         percentile_cont(0.5) within group (order by abs(val - (select v from m))),
         count(*)::int
    from samples
$$;

do $$
declare fn text;
begin
  foreach fn in array array[
    'error_issue_record_occurrences(text,uuid,timestamptz[],text[],text[])',
    'route_error_issue_notifications(integer)',
    'issue_metric_observable_since(text,uuid)',
    'issue_metric_window(text,uuid,text,text,timestamptz,timestamptz)',
    'issue_metric_baseline(text,uuid,text,text,integer,integer)'
  ] loop
    execute format('revoke execute on function public.%s from public', fn);
    if exists (select 1 from pg_roles where rolname = 'anon') then
      execute format('revoke execute on function public.%s from anon', fn);
    end if;
    if exists (select 1 from pg_roles where rolname = 'authenticated') then
      execute format('revoke execute on function public.%s from authenticated', fn);
    end if;
  end loop;
end $$;

-- Reprise intégrale de migration-v68, plus :
--   • issue:<uuid> — somme des occurrences observées sur la fenêtre de la règle ;
--   • no_data explicite (fenêtre non observable, aucune mesure, comparables
--     insuffisants), écrit dans alert_rule.last_* comme ok et breached ;
--   • le pic d'une issue part dans l'outbox sous la clé spike:<règle>:<fenêtre>,
--     avec le même délai de grâce que les autres règles.
create or replace function check_alerts() returns integer
  language plpgsql security definer set search_path to 'public', 'pg_temp'
as $function$
declare r record; v double precision; fired int := 0; ev_id bigint; req_id bigint;
        b record; breached boolean; msg text; lo double precision; hi double precision;
        event_sample_rate double precision;
        issue uuid; observable timestamptz; no_data text; inserees int;
begin
  for r in select * from alert_rule where active order by id loop
    -- Sérialise deux schedulers concurrents règle par règle. L'ordre par id
    -- empêche aussi un interblocage quand plusieurs règles sont actives.
    perform pg_advisory_xact_lock(r.id);
    v := null; event_sample_rate := null; no_data := null; issue := null;
    if r.metric = 'error_rate' then
      select coalesce(sum(e.occurrences), 0)::float / greatest((select count(*) from rum_pageview p
               where p.app_id = r.app_id and (r.route is null or p.route = r.route)
                 and p.started_at > now() - (r.window_minutes || ' minutes')::interval), 1)
        into v from rum_error e
       where e.app_id = r.app_id and e.ts > now() - (r.window_minutes || ' minutes')::interval
         and (r.route is null or e.route = r.route);
    elsif r.metric = 'ai_cost' then
      select coalesce(sum(a.cost_usd), 0)::float into v from rum_ai a
       where a.app_id = r.app_id and a.ts > now() - (r.window_minutes || ' minutes')::interval
         and (r.route is null or a.route = r.route);
    elsif r.metric = 'log_errors' then
      select count(*)::float into v from rum_log l
       where l.app_id = r.app_id and l.severity_num >= 17
         and l.ts > now() - (r.window_minutes || ' minutes')::interval
         and (r.route is null or l.route = r.route);
    elsif r.metric like 'event:%' then
      select count(*)::float, min(coalesce(s.sample_rate, 1))::double precision
        into v, event_sample_rate
        from rum_event_index i
        join rum_event e
          on i.kind = 'event' and e.app_id = i.app_id and e.span_id = i.source_span_id
        left join rum_session s
          on s.app_id = i.app_id and s.session_id = i.session_id
       where i.app_id = r.app_id and e.name = substring(r.metric from 7)
         and coalesce(e.event_type, 'custom') = 'custom'
         and i.ts > now() - (r.window_minutes || ' minutes')::interval
         and i.ts <= now()
         and (r.route is null or i.route = r.route);
    elsif r.metric like 'issue:%' then
      issue := substring(r.metric from 7)::uuid;
      observable := issue_metric_observable_since(r.app_id, issue);
      if observable is null then
        no_data := 'issue absente de l''app ou regroupement v2 inactif';
      elsif observable > now() - (r.window_minutes || ' minutes')::interval then
        no_data := 'fenêtre incomplète : issue observable depuis '
                   || to_char(observable at time zone 'UTC', 'YYYY-MM-DD HH24:MI') || ' UTC';
      else
        select w.occurrences, w.min_inclusion into v, event_sample_rate
          from issue_metric_window(r.app_id, issue, r.route, r.env,
                                   now() - (r.window_minutes || ' minutes')::interval, now()) w;
      end if;
    else
      select percentile_cont(0.75) within group (order by m.value) into v from rum_metric m
       where m.app_id = r.app_id and m.name = r.metric
         and m.ts > now() - (r.window_minutes || ' minutes')::interval
         and (r.route is null or m.route = r.route);
    end if;

    breached := false; msg := null;
    if v is null then
      no_data := coalesce(no_data, 'aucune mesure sur la fenêtre');
    elsif r.mode = 'baseline' then
      if r.metric like 'event:%' then
        select * into b from event_metric_baseline(
          r.app_id, r.metric, r.route, r.baseline_weeks, r.window_minutes
        );
      elsif r.metric like 'issue:%' then
        select * into b from issue_metric_baseline(
          r.app_id, issue, r.route, r.env, r.baseline_weeks, r.window_minutes
        );
      else
        select * into b from metric_baseline(r.app_id, r.metric, r.route, r.baseline_weeks);
      end if;
      if b.n >= 4 and b.mad is not null then
        hi := b.med + r.sensitivity * b.mad;
        lo := b.med - r.sensitivity * b.mad;
        -- Une série parfaitement stable (souvent zéro pour un événement rare)
        -- a MAD=0 : le moindre écart dans le sens demandé est alors anormal.
        breached := (r.comparator = '>' and v > hi) or (r.comparator = '<' and v < lo);
        if breached then
          msg := case when b.mad > 0 then
            format('%s %s %s anormal (normal≈%s, écart %sσ_MAD, fenêtre %s min, app %s%s)',
              r.metric, r.comparator, round(v::numeric,1), round(b.med::numeric,1),
              round((abs(v - b.med)/b.mad)::numeric,1), r.window_minutes, r.app_id,
              coalesce(', route ' || left(r.route, 200), ''))
          else
            format('%s %s %s anormal (normal stable≈%s, MAD=0, fenêtre %s min, app %s%s)',
              r.metric, r.comparator, round(v::numeric,1), round(b.med::numeric,1),
              r.window_minutes, r.app_id, coalesce(', route ' || left(r.route, 200), ''))
          end;
        end if;
      else
        no_data := format('%s fenêtre(s) comparable(s), 4 requises', coalesce(b.n, 0));
      end if;
    else
      breached := (r.comparator = '>' and v > r.threshold) or (r.comparator = '<' and v < r.threshold);
      if breached then
        msg := format('%s %s %s (seuil %s, fenêtre %s min, app %s%s)',
          r.metric, r.comparator, round(v::numeric,1), r.threshold, r.window_minutes, r.app_id,
          coalesce(', route ' || left(r.route, 200), ''));
      end if;
    end if;

    if breached and r.metric like 'event:%' and event_sample_rate > 0 and event_sample_rate < 1 then
      msg := msg || format(
        ' — comptes observés sur un échantillon (taux minimal %s%%), sans extrapolation',
        round((event_sample_rate * 100)::numeric, 1)
      );
    elsif breached and r.metric like 'issue:%' then
      msg := msg || coalesce(' — env ' || r.env, '');
      if event_sample_rate > 0 and event_sample_rate < 1 then
        msg := msg || format(
          ' — occurrences observées sur un échantillon (probabilité d''inclusion minimale %s%%), sans extrapolation',
          round((event_sample_rate * 100)::numeric, 1)
        );
      end if;
    end if;

    update alert_rule
       set last_evaluated_at = now(),
           last_state = case when no_data is not null then 'no_data' when breached then 'breached' else 'ok' end,
           last_value = v,
           last_reason = left(no_data, 300)
     where id = r.id;

    if breached and r.metric like 'issue:%' then
      if not exists (select 1 from alert_event ae
                      where ae.rule_id = r.id and not ae.acknowledged
                        and ae.fired_at > now() - (r.window_minutes || ' minutes')::interval)
         and not exists (select 1 from error_issue_notification n
                          where n.rule_id = r.id and n.state = 'pending') then
        insert into error_issue_notification (app_id, issue_id, kind, rule_id, event_key, payload)
        values (
          r.app_id, issue, 'spike', r.id,
          format('spike:%s:%s', r.id, floor(extract(epoch from now()) / (r.window_minutes * 60))::bigint),
          jsonb_build_object(
            'source', 'mip-rum', 'kind', 'spike', 'app_id', r.app_id, 'issue_id', issue, 'metric', r.metric,
            'route', left(r.route, 200), 'env', r.env, 'value', round(v::numeric, 1), 'severity', r.severity,
            'text', '[MIP RUM] ' || left(msg, 1500))
        )
        on conflict (event_key) do nothing;
        get diagnostics inserees = row_count;
        fired := fired + inserees;
      end if;
    elsif breached and not exists (select 1 from alert_event ae
                      where ae.rule_id = r.id and not ae.acknowledged
                        and ae.fired_at > now() - (r.window_minutes || ' minutes')::interval) then
      insert into alert_event (rule_id, value, message, severity)
      values (r.id, v, msg, r.severity) returning id into ev_id;
      fired := fired + 1;
      if r.webhook_url is not null then
        insert into alert_delivery (alert_event_id, target) values (ev_id, r.webhook_url);
        begin
          select net.http_post(url := r.webhook_url,
            body := jsonb_build_object('source','mip-rum','app_id',r.app_id,'metric',r.metric,
              'route',r.route,'value',round(v::numeric,1),'severity',r.severity,'text',msg))
            into req_id;
          update alert_delivery set status='sent', response='pg_net request '||req_id
            where alert_event_id = ev_id and target = r.webhook_url;
        exception when others then null; end;
      end if;
      perform route_alert(ev_id, r.app_id, r.severity, '[MIP RUM] ' || msg,
        jsonb_build_object('source','mip-rum','app_id',r.app_id,'metric',r.metric,
          'route',r.route,'value',round(v::numeric,1),'severity',r.severity,'text',msg));
    end if;
  end loop;
  return fired;
end $function$;

-- ── 9. Livraison des alertes sans règle ─────────────────────────────────────
-- Le dispatcher local ne livrait que les événements d'une règle (jointure
-- interne) : nouvelles erreurs, SLO, uptime restaient `queued` sans fin. Il les
-- prend désormais en charge, mais seulement ceux déclenchés depuis cette date :
-- l'arriéré, lui, est soldé ici avec sa raison au lieu de partir d'un coup.
-- `coalesce` : un rejeu garde la date de la première application.
alter table alert_config add column if not exists rule_less_dispatch_since timestamptz;
update alert_config set rule_less_dispatch_since = coalesce(rule_less_dispatch_since, now()) where singleton;

comment on column alert_config.rule_less_dispatch_since is
  'Le dispatcher local livre les alertes sans règle déclenchées depuis cette date (v73) ; l''arriéré est soldé en skipped';

update alert_delivery d
   set status = 'skipped',
       response = 'arriéré antérieur à la livraison des alertes sans règle (v73) : jamais envoyé'
  from alert_event e, alert_config c
 where d.alert_event_id = e.id and d.status = 'queued'
   and e.rule_id is null and c.singleton and e.fired_at < c.rule_less_dispatch_since;
