// Mapping IANA timezone -> code pays ISO 3166-1 alpha-2 (v0.3, ROADMAP B1).
// Géo RGPD-friendly : déduit du fuseau envoyé par le SDK (mip.tz), zéro IP stockée.
// ~250 zones majeures : Europe complète, Amériques, Asie principales, Afrique
// francophone + grands hubs, Océanie ; fallback par préfixe pour les zones
// rangées par pays (America/Argentina/*, Australia/*, alias legacy US/* …).
// JS pur, sans dépendance : importé par Node (dev-server) et Deno (edge function).

const TZ_COUNTRY = {
  // --- Europe (complète) ------------------------------------------------------
  "Europe/Paris": "FR",
  "Europe/London": "GB",
  "Europe/Dublin": "IE",
  "Europe/Lisbon": "PT",
  "Europe/Madrid": "ES",
  "Europe/Andorra": "AD",
  "Europe/Monaco": "MC",
  "Europe/Brussels": "BE",
  "Europe/Amsterdam": "NL",
  "Europe/Luxembourg": "LU",
  "Europe/Berlin": "DE",
  "Europe/Busingen": "DE",
  "Europe/Zurich": "CH",
  "Europe/Vaduz": "LI",
  "Europe/Vienna": "AT",
  "Europe/Rome": "IT",
  "Europe/Vatican": "VA",
  "Europe/San_Marino": "SM",
  "Europe/Malta": "MT",
  "Europe/Gibraltar": "GI",
  "Europe/Copenhagen": "DK",
  "Europe/Stockholm": "SE",
  "Europe/Oslo": "NO",
  "Europe/Helsinki": "FI",
  "Europe/Reykjavik": "IS",
  "Europe/Tallinn": "EE",
  "Europe/Riga": "LV",
  "Europe/Vilnius": "LT",
  "Europe/Warsaw": "PL",
  "Europe/Prague": "CZ",
  "Europe/Bratislava": "SK",
  "Europe/Budapest": "HU",
  "Europe/Ljubljana": "SI",
  "Europe/Zagreb": "HR",
  "Europe/Sarajevo": "BA",
  "Europe/Belgrade": "RS",
  "Europe/Podgorica": "ME",
  "Europe/Skopje": "MK",
  "Europe/Tirane": "AL",
  "Europe/Athens": "GR",
  "Europe/Sofia": "BG",
  "Europe/Bucharest": "RO",
  "Europe/Chisinau": "MD",
  "Europe/Kyiv": "UA",
  "Europe/Kiev": "UA", // alias pré-2022
  "Europe/Uzhgorod": "UA",
  "Europe/Zaporozhye": "UA",
  "Europe/Simferopol": "UA",
  "Europe/Minsk": "BY",
  "Europe/Moscow": "RU",
  "Europe/Kaliningrad": "RU",
  "Europe/Volgograd": "RU",
  "Europe/Samara": "RU",
  "Europe/Saratov": "RU",
  "Europe/Astrakhan": "RU",
  "Europe/Kirov": "RU",
  "Europe/Ulyanovsk": "RU",
  "Europe/Istanbul": "TR",
  "Europe/Jersey": "JE",
  "Europe/Guernsey": "GG",
  "Europe/Isle_of_Man": "IM",
  "Atlantic/Canary": "ES",
  "Atlantic/Madeira": "PT",
  "Atlantic/Azores": "PT",
  "Atlantic/Faroe": "FO",
  "Atlantic/Reykjavik": "IS",

  // --- Amérique du Nord -------------------------------------------------------
  "America/New_York": "US",
  "America/Chicago": "US",
  "America/Denver": "US",
  "America/Phoenix": "US",
  "America/Los_Angeles": "US",
  "America/Anchorage": "US",
  "America/Adak": "US",
  "America/Juneau": "US",
  "America/Sitka": "US",
  "America/Nome": "US",
  "America/Yakutat": "US",
  "America/Metlakatla": "US",
  "America/Boise": "US",
  "America/Detroit": "US",
  "America/Menominee": "US",
  "Pacific/Honolulu": "US",
  "America/Toronto": "CA",
  "America/Montreal": "CA", // alias legacy
  "America/Vancouver": "CA",
  "America/Edmonton": "CA",
  "America/Winnipeg": "CA",
  "America/Regina": "CA",
  "America/Halifax": "CA",
  "America/Moncton": "CA",
  "America/St_Johns": "CA",
  "America/Whitehorse": "CA",
  "America/Yellowknife": "CA",
  "America/Iqaluit": "CA",
  "America/Mexico_City": "MX",
  "America/Cancun": "MX",
  "America/Monterrey": "MX",
  "America/Tijuana": "MX",
  "America/Chihuahua": "MX",
  "America/Merida": "MX",
  "America/Mazatlan": "MX",
  "America/Hermosillo": "MX",
  "America/Nuuk": "GL",
  "America/Godthab": "GL", // alias pré-2020
  "America/Miquelon": "PM",
  "Atlantic/Bermuda": "BM",

  // --- Amérique centrale & Caraïbes -------------------------------------------
  "America/Guatemala": "GT",
  "America/El_Salvador": "SV",
  "America/Tegucigalpa": "HN",
  "America/Managua": "NI",
  "America/Costa_Rica": "CR",
  "America/Panama": "PA",
  "America/Belize": "BZ",
  "America/Havana": "CU",
  "America/Jamaica": "JM",
  "America/Port-au-Prince": "HT",
  "America/Santo_Domingo": "DO",
  "America/Puerto_Rico": "PR",
  "America/Nassau": "BS",
  "America/Barbados": "BB",
  "America/Port_of_Spain": "TT",
  "America/Curacao": "CW",
  "America/Aruba": "AW",
  "America/Martinique": "MQ",
  "America/Guadeloupe": "GP",
  "America/Cayman": "KY",
  "America/Grand_Turk": "TC",

  // --- Amérique du Sud ---------------------------------------------------------
  "America/Bogota": "CO",
  "America/Caracas": "VE",
  "America/Guayaquil": "EC",
  "Pacific/Galapagos": "EC",
  "America/Lima": "PE",
  "America/La_Paz": "BO",
  "America/Santiago": "CL",
  "America/Punta_Arenas": "CL",
  "Pacific/Easter": "CL",
  "America/Asuncion": "PY",
  "America/Montevideo": "UY",
  "America/Buenos_Aires": "AR", // alias legacy (zones modernes via préfixe)
  "America/Sao_Paulo": "BR",
  "America/Bahia": "BR",
  "America/Fortaleza": "BR",
  "America/Recife": "BR",
  "America/Belem": "BR",
  "America/Manaus": "BR",
  "America/Cuiaba": "BR",
  "America/Campo_Grande": "BR",
  "America/Boa_Vista": "BR",
  "America/Porto_Velho": "BR",
  "America/Rio_Branco": "BR",
  "America/Santarem": "BR",
  "America/Maceio": "BR",
  "America/Araguaina": "BR",
  "America/Noronha": "BR",
  "America/Guyana": "GY",
  "America/Paramaribo": "SR",
  "America/Cayenne": "GF",

  // --- Asie (principales) ------------------------------------------------------
  "Asia/Tokyo": "JP",
  "Asia/Seoul": "KR",
  "Asia/Pyongyang": "KP",
  "Asia/Shanghai": "CN",
  "Asia/Chongqing": "CN", // alias legacy
  "Asia/Urumqi": "CN",
  "Asia/Hong_Kong": "HK",
  "Asia/Macau": "MO",
  "Asia/Taipei": "TW",
  "Asia/Manila": "PH",
  "Asia/Singapore": "SG",
  "Asia/Kuala_Lumpur": "MY",
  "Asia/Kuching": "MY",
  "Asia/Brunei": "BN",
  "Asia/Jakarta": "ID",
  "Asia/Pontianak": "ID",
  "Asia/Makassar": "ID",
  "Asia/Jayapura": "ID",
  "Asia/Dili": "TL",
  "Asia/Bangkok": "TH",
  "Asia/Ho_Chi_Minh": "VN",
  "Asia/Saigon": "VN", // alias legacy
  "Asia/Phnom_Penh": "KH",
  "Asia/Vientiane": "LA",
  "Asia/Yangon": "MM",
  "Asia/Rangoon": "MM", // alias legacy
  "Asia/Kolkata": "IN",
  "Asia/Calcutta": "IN", // alias legacy
  "Asia/Colombo": "LK",
  "Asia/Dhaka": "BD",
  "Asia/Kathmandu": "NP",
  "Asia/Thimphu": "BT",
  "Asia/Karachi": "PK",
  "Asia/Kabul": "AF",
  "Asia/Tehran": "IR",
  "Asia/Baghdad": "IQ",
  "Asia/Riyadh": "SA",
  "Asia/Kuwait": "KW",
  "Asia/Bahrain": "BH",
  "Asia/Qatar": "QA",
  "Asia/Dubai": "AE",
  "Asia/Muscat": "OM",
  "Asia/Aden": "YE",
  "Asia/Amman": "JO",
  "Asia/Beirut": "LB",
  "Asia/Damascus": "SY",
  "Asia/Jerusalem": "IL",
  "Asia/Tel_Aviv": "IL", // alias legacy
  "Asia/Gaza": "PS",
  "Asia/Hebron": "PS",
  "Asia/Nicosia": "CY",
  "Asia/Famagusta": "CY",
  "Asia/Baku": "AZ",
  "Asia/Yerevan": "AM",
  "Asia/Tbilisi": "GE",
  "Asia/Almaty": "KZ",
  "Asia/Aqtobe": "KZ",
  "Asia/Atyrau": "KZ",
  "Asia/Oral": "KZ",
  "Asia/Qostanay": "KZ",
  "Asia/Qyzylorda": "KZ",
  "Asia/Tashkent": "UZ",
  "Asia/Samarkand": "UZ",
  "Asia/Bishkek": "KG",
  "Asia/Dushanbe": "TJ",
  "Asia/Ashgabat": "TM",
  "Asia/Ulaanbaatar": "MN",
  "Asia/Hovd": "MN",
  "Asia/Choibalsan": "MN",
  "Asia/Yekaterinburg": "RU",
  "Asia/Omsk": "RU",
  "Asia/Novosibirsk": "RU",
  "Asia/Barnaul": "RU",
  "Asia/Tomsk": "RU",
  "Asia/Novokuznetsk": "RU",
  "Asia/Krasnoyarsk": "RU",
  "Asia/Irkutsk": "RU",
  "Asia/Chita": "RU",
  "Asia/Yakutsk": "RU",
  "Asia/Vladivostok": "RU",
  "Asia/Magadan": "RU",
  "Asia/Sakhalin": "RU",
  "Asia/Kamchatka": "RU",
  "Asia/Anadyr": "RU",

  // --- Afrique (francophone + grands hubs) -------------------------------------
  "Africa/Casablanca": "MA",
  "Africa/El_Aaiun": "EH",
  "Africa/Algiers": "DZ",
  "Africa/Tunis": "TN",
  "Africa/Tripoli": "LY",
  "Africa/Cairo": "EG",
  "Africa/Ceuta": "ES",
  "Africa/Dakar": "SN",
  "Africa/Nouakchott": "MR",
  "Africa/Bamako": "ML",
  "Africa/Conakry": "GN",
  "Africa/Abidjan": "CI",
  "Africa/Ouagadougou": "BF",
  "Africa/Niamey": "NE",
  "Africa/Lome": "TG",
  "Africa/Porto-Novo": "BJ",
  "Africa/Lagos": "NG",
  "Africa/Accra": "GH",
  "Africa/Freetown": "SL",
  "Africa/Monrovia": "LR",
  "Africa/Banjul": "GM",
  "Africa/Bissau": "GW",
  "Africa/Sao_Tome": "ST",
  "Africa/Malabo": "GQ",
  "Africa/Douala": "CM",
  "Africa/Ndjamena": "TD",
  "Africa/Bangui": "CF",
  "Africa/Libreville": "GA",
  "Africa/Brazzaville": "CG",
  "Africa/Kinshasa": "CD",
  "Africa/Lubumbashi": "CD",
  "Africa/Bujumbura": "BI",
  "Africa/Kigali": "RW",
  "Africa/Djibouti": "DJ",
  "Africa/Mogadishu": "SO",
  "Africa/Addis_Ababa": "ET",
  "Africa/Asmara": "ER",
  "Africa/Khartoum": "SD",
  "Africa/Juba": "SS",
  "Africa/Nairobi": "KE",
  "Africa/Kampala": "UG",
  "Africa/Dar_es_Salaam": "TZ",
  "Africa/Lusaka": "ZM",
  "Africa/Harare": "ZW",
  "Africa/Maputo": "MZ",
  "Africa/Luanda": "AO",
  "Africa/Windhoek": "NA",
  "Africa/Gaborone": "BW",
  "Africa/Johannesburg": "ZA",
  "Africa/Maseru": "LS",
  "Africa/Mbabane": "SZ",
  "Africa/Blantyre": "MW",
  "Indian/Antananarivo": "MG",
  "Indian/Mauritius": "MU",
  "Indian/Reunion": "RE",
  "Indian/Mayotte": "YT",
  "Indian/Comoro": "KM",
  "Indian/Mahe": "SC",
  "Atlantic/Cape_Verde": "CV",

  // --- Océanie ------------------------------------------------------------------
  "Pacific/Auckland": "NZ",
  "Pacific/Chatham": "NZ",
  "Pacific/Fiji": "FJ",
  "Pacific/Port_Moresby": "PG",
  "Pacific/Guadalcanal": "SB",
  "Pacific/Noumea": "NC",
  "Pacific/Tahiti": "PF",
  "Pacific/Marquesas": "PF",
  "Pacific/Gambier": "PF",
  "Pacific/Wallis": "WF",
  "Pacific/Apia": "WS",
  "Pacific/Tongatapu": "TO",
  "Pacific/Guam": "GU",
  "Pacific/Saipan": "MP",
  "Pacific/Palau": "PW",
  "Pacific/Majuro": "MH",
  "Pacific/Tarawa": "KI",
  "Pacific/Funafuti": "TV",
  "Pacific/Norfolk": "NF",
  "Pacific/Pitcairn": "PN",
};

// Préfixes -> pays, uniquement quand le préfixe implique un pays sans ambiguïté
// (zones rangées par pays + alias legacy tzdb). 'Europe/', 'Asia/'… restent null.
const TZ_PREFIX = [
  ["America/Argentina/", "AR"],
  ["America/Indiana/", "US"],
  ["America/Kentucky/", "US"],
  ["America/North_Dakota/", "US"],
  ["Antarctica/", "AQ"],
  ["Australia/", "AU"],
  ["US/", "US"],
  ["Canada/", "CA"],
  ["Mexico/", "MX"],
  ["Brazil/", "BR"],
  ["Chile/", "CL"],
];

/**
 * Timezone IANA -> code pays ISO alpha-2, null si inconnue.
 * Lookup exact puis fallback par préfixe ('America/Argentina/Ushuaia' -> 'AR').
 */
export function tzToCountry(tz) {
  if (typeof tz !== "string" || !tz) return null;
  const exact = TZ_COUNTRY[tz];
  if (exact) return exact;
  for (const [prefix, country] of TZ_PREFIX) {
    if (tz.startsWith(prefix)) return country;
  }
  return null;
}
